import { Link } from "wouter";
import { Navbar } from "@/components/Navbar";
import { BrandLogo } from "@/components/BrandLogo";

export default function Terms() {
  return (
    <div className="page">
      <Navbar variant="full" />
      <main className="container-tight py-12 sm:py-16">
        <div className="max-w-3xl mx-auto space-y-6 text-sm text-muted-foreground">
          <h1 className="text-2xl font-bold text-foreground mb-1">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mt-1">Last updated: April 2, 2026</p>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. Agreement to Terms</h2>
            <p>
              By downloading, installing, accessing, or using the Axiom application and related services (collectively, the "Service"), operated by Axiom ("we," "us," or "our"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy, which is incorporated herein by reference. If you do not agree to these Terms, do not use the Service. These Terms constitute a legally binding agreement between you and Axiom.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. Description of Service</h2>
            <p>
              Axiom provides an AI-powered strength training and fitness platform that includes: lift diagnostic analysis, personalized training program generation, AI-powered coaching conversations, nutrition guidance and meal photo analysis, wellness tracking, exercise demonstration videos, social features (feed, friend connections, and direct messaging), and related tools. The Service is available via our website and mobile applications for iOS and Android.
            </p>
            <p className="mt-2">
              All content, recommendations, programs, analyses, and responses generated by the Service — including those produced by artificial intelligence — are for <strong>general informational and educational purposes only</strong> and do not constitute professional medical, nutritional, or fitness advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. Medical and Health Disclaimer — PLEASE READ CAREFULLY</h2>
            <p className="font-semibold text-foreground">
              THE SERVICE DOES NOT PROVIDE MEDICAL ADVICE, MEDICAL DIAGNOSIS, OR PROFESSIONAL HEALTHCARE SERVICES OF ANY KIND.
            </p>
            <p className="mt-2">
              All content provided through the Service, including AI-generated lift diagnostics, training programs, nutrition estimates, coaching responses, calorie calculations, and wellness recommendations, is for general informational purposes only. It is <strong>not</strong> a substitute for professional medical advice, diagnosis, or treatment from a licensed physician, registered dietitian, certified personal trainer, physical therapist, or other qualified healthcare professional.
            </p>
            <p className="mt-2">
              <strong>Before beginning any exercise program, changing your diet, or making decisions about your health based on information from the Service:</strong> consult with a qualified healthcare professional, particularly if you have any pre-existing medical conditions, injuries, pregnancy, cardiovascular risk factors, or other health concerns.
            </p>
            <p className="mt-2">
              Never disregard professional medical advice or delay seeking it because of something you received through the Service. If you experience pain, injury, dizziness, shortness of breath, or other symptoms during exercise, stop immediately and seek medical attention.
            </p>
            <p className="mt-2">
              Nutrition analysis from food photos is an <strong>estimate only</strong> and may be inaccurate. Do not rely on it for medical nutrition therapy or the management of any health condition.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. Assumption of Risk; Physical Activity Warning</h2>
            <p>
              <strong>PHYSICAL EXERCISE INVOLVES INHERENT RISKS, INCLUDING THE RISK OF SERIOUS INJURY OR DEATH.</strong> By using the Service to guide your physical training, you expressly acknowledge and voluntarily assume all risks associated with physical activity, including risks from following AI-generated training programs and recommendations.
            </p>
            <p className="mt-2">
              You represent and warrant that: (a) you are physically capable of participating in the exercise activities described in the Service; (b) you have consulted or will consult a physician before beginning any exercise program recommended by the Service, or you knowingly and voluntarily waive that consultation and assume all associated risks; and (c) you will use good judgment and stop any activity that causes pain or discomfort.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. AI-Generated Content Disclaimer</h2>
            <p>
              The Service uses artificial intelligence models — including those from OpenAI and Google (Gemini) — to generate diagnostics, training programs, nutritional analyses, and coaching responses. You acknowledge that:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>AI-generated content may contain errors, inaccuracies, omissions, or outputs that are unsuitable for your specific situation.</li>
              <li>AI outputs are generated probabilistically and are not guaranteed to be accurate, complete, safe, or appropriate for any individual.</li>
              <li>You are solely responsible for evaluating, verifying, and deciding whether to follow any AI-generated recommendation.</li>
              <li>Meal photo calorie estimates are approximations and should not be relied upon for medical nutrition management.</li>
              <li>We do not guarantee that the AI coach will always respond within the defined safety scope; you should exercise independent judgment when reviewing all outputs.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">6. Release of Liability and Indemnification</h2>
            <p>
              To the maximum extent permitted by applicable law, you hereby release, discharge, and hold harmless Axiom and its officers, directors, employees, agents, contractors, licensors, and affiliates (collectively, "Axiom Parties") from any and all claims, demands, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from or related to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Your use of or inability to use the Service;</li>
              <li>Any physical injury, illness, death, or property damage resulting from activities undertaken based on information from the Service;</li>
              <li>Your reliance on any AI-generated content, recommendation, program, or analysis;</li>
              <li>Inaccurate nutrition estimates or dietary guidance;</li>
              <li>Content posted by other users;</li>
              <li>Unauthorized access to or alteration of your data;</li>
              <li>Any other matter relating to the Service.</li>
            </ul>
            <p className="mt-2">
              You agree to indemnify and defend the Axiom Parties against any claims arising from your use of the Service, your violation of these Terms, your User Content, or your violation of any rights of another party.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">7. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT.
            </p>
            <p className="mt-2">
              IN NO EVENT SHALL THE AXIOM PARTIES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR PHYSICAL HARM, ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="mt-2">
              OUR TOTAL CUMULATIVE LIABILITY FOR ANY AND ALL CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNT YOU PAID AXIOM IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS (USD $100).
            </p>
            <p className="mt-2">
              SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR LIMITATION OF LIABILITY, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">8. Eligibility and Account Registration</h2>
            <p>
              You must be at least 18 years of age and legally capable of entering into a binding contract to use the Service. By using the Service, you represent and warrant that you meet these requirements. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization.
            </p>
            <p className="mt-2">
              You are responsible for: (a) providing accurate, current, and complete registration information; (b) maintaining the confidentiality of your account credentials; (c) all activity that occurs under your account; and (d) notifying us immediately of any unauthorized use of your account at <a href="mailto:support@axiomtraining.io" className="text-primary hover:underline">support@axiomtraining.io</a>.
            </p>
            <p className="mt-2">
              <strong>Usernames:</strong> You may set a unique username for your account. Usernames must be 3–30 characters, contain only letters, numbers, or underscores, and must not impersonate another person, be offensive, or violate third-party rights. We reserve the right to reclaim or modify usernames that violate these rules.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">9. Subscriptions, Payments, and Auto-Renewal</h2>
            <p>
              Certain features of the Service require a paid Pro subscription. All billing is processed by Stripe. By subscribing, you authorize Axiom (via Stripe) to charge your payment method on a recurring basis at the applicable subscription rate until you cancel.
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li><strong>Auto-renewal:</strong> Subscriptions automatically renew at the end of each billing period (monthly or annually, as selected) unless cancelled before the renewal date.</li>
              <li><strong>Cancellation:</strong> You may cancel at any time through your account settings or the Stripe billing portal. Cancellation takes effect at the end of the current billing period; you retain access until then. No partial refunds are issued for unused time.</li>
              <li><strong>Price changes:</strong> We may change subscription pricing with at least 30 days' notice. Continued use after the effective date constitutes acceptance of the new price.</li>
              <li><strong>Refunds:</strong> Subscription fees are non-refundable except as required by applicable law or at our sole discretion in exceptional circumstances.</li>
              <li><strong>Free tier limits:</strong> Free accounts may be subject to usage limits (e.g., number of AI analyses per day) which may change over time.</li>
            </ul>
            <p className="mt-2">
              <strong>Note for iOS users:</strong> Axiom subscriptions are managed outside of the Apple App Store and Apple is not a party to the subscription agreement. Apple has no responsibility for subscription billing, cancellation, or refunds.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">10. User-Generated Content and Social Features</h2>
            <p>
              The Service allows you to create, post, and share content including text posts, workout data, training programs, images, and messages ("User Content"). By submitting User Content, you:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Retain ownership of your User Content.</li>
              <li>Grant Axiom a worldwide, non-exclusive, royalty-free license to store, display, and process your User Content solely to operate and provide the Service.</li>
              <li>Represent that you have the rights to post such content and that it does not violate any third-party rights or applicable laws.</li>
            </ul>
            <p className="mt-2">You agree not to post User Content that:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Is unlawful, harmful, abusive, harassing, defamatory, obscene, or otherwise objectionable;</li>
              <li>Infringes any copyright, trademark, or other intellectual property or privacy rights;</li>
              <li>Contains misinformation about health, medicine, or fitness that could cause harm;</li>
              <li>Promotes dangerous, extreme, or eating-disordered behaviors;</li>
              <li>Contains personal information of other individuals without their consent;</li>
              <li>Constitutes spam or unsolicited commercial communications.</li>
            </ul>
            <p className="mt-2">
              We reserve the right (but not the obligation) to remove any User Content that violates these Terms or that we determine in our sole discretion to be harmful, inappropriate, or otherwise objectionable. We are not liable for any User Content posted by users.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">11. Acceptable Use Policy</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Violate any applicable local, national, or international law or regulation;</li>
              <li>Attempt to gain unauthorized access to any part of the Service, other user accounts, or our infrastructure;</li>
              <li>Circumvent, disable, or interfere with security features of the Service;</li>
              <li>Scrape, crawl, harvest, or systematically extract data from the Service without our written permission;</li>
              <li>Attempt to "jailbreak," manipulate, or circumvent the AI coach's safety guidelines;</li>
              <li>Impersonate any person or entity or misrepresent your affiliation;</li>
              <li>Transmit malware, viruses, or other harmful code;</li>
              <li>Use the Service for any commercial purpose not expressly permitted;</li>
              <li>Harass, bully, or harm other users.</li>
            </ul>
            <p className="mt-2">Violation of these rules may result in immediate suspension or termination of your account without notice or refund.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">12. Account Deletion</h2>
            <p>
              You may delete your account at any time by contacting us at <a href="mailto:support@axiomtraining.io" className="text-primary hover:underline">support@axiomtraining.io</a> with the subject "Account Deletion Request." Upon deletion, your personal data will be removed from our active systems within 30 days, subject to our data retention obligations (see Privacy Policy). Cancellation of your account does not automatically cancel your active subscription — you must cancel your subscription separately through the billing portal to stop future charges.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">13. Intellectual Property</h2>
            <p>
              The Service — including its design, software, branding, algorithms, and content we create — is owned by or licensed to Axiom and is protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, reverse engineer, distribute, or create derivative works from any part of the Service without our express written permission.
            </p>
            <p className="mt-2">
              You retain all ownership rights in the User Content you submit. The license you grant us terminates when you delete the content or your account, subject to any copies made in backups which will be purged in accordance with our retention schedule.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">14. Third-Party Services and Links</h2>
            <p>
              The Service integrates with and links to third-party services including OpenAI, Google (Gemini, OAuth, YouTube), Stripe, Twilio, and Expo. Your use of those services is governed by their respective terms of service and privacy policies. We are not responsible for the practices, content, or availability of any third-party service. YouTube video content embedded in the Service is subject to YouTube's Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">15. Affiliate Program</h2>
            <p>
              Axiom operates an affiliate referral program. Affiliates earn commissions on referred subscriptions in accordance with their affiliate agreement. Axiom reserves the right to modify, suspend, or terminate the affiliate program at any time. Commission payments are subject to Stripe's connected account terms. Axiom is not liable for any taxes owed by affiliates on commission payments.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">16. DMCA and Copyright Infringement</h2>
            <p>
              We respect intellectual property rights. If you believe any content on the Service infringes your copyright, please send a notice to <a href="mailto:legal@axiomtraining.io" className="text-primary hover:underline">legal@axiomtraining.io</a> containing: (a) a description of the copyrighted work; (b) identification of the infringing content and its location on the Service; (c) your contact information; (d) a statement of good faith belief; and (e) a statement under penalty of perjury that you are the copyright owner or authorized to act on their behalf.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">17. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, with or without cause or notice, including for violation of these Terms, non-payment, conduct that harms other users or our reputation, or any reason we deem appropriate in our sole discretion. Upon termination, your right to use the Service ceases immediately. Provisions of these Terms that by their nature should survive termination will survive, including Sections 3–7, 13, 18, and 19.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">18. Dispute Resolution and Arbitration</h2>
            <p>
              <strong>Please read this section carefully — it affects your legal rights.</strong>
            </p>
            <p className="mt-2">
              Any dispute, claim, or controversy arising from or relating to these Terms or the Service (a "Dispute") shall be resolved exclusively by binding individual arbitration administered by the American Arbitration Association (AAA) under its Consumer Arbitration Rules, rather than in a court of law. You and Axiom each waive the right to a jury trial and the right to participate in a class action, class arbitration, or representative proceeding.
            </p>
            <p className="mt-2">
              <strong>Exception:</strong> Either party may seek injunctive or other equitable relief in a court of competent jurisdiction for claims involving intellectual property, unauthorized access, or where immediate relief is necessary to prevent irreparable harm.
            </p>
            <p className="mt-2">
              <strong>Opt-out:</strong> You may opt out of this arbitration agreement by sending written notice to <a href="mailto:legal@axiomtraining.io" className="text-primary hover:underline">legal@axiomtraining.io</a> within 30 days of first accepting these Terms. Your notice must include your name, email, and a clear statement that you are opting out of arbitration.
            </p>
            <p className="mt-2">
              The arbitration shall be conducted in English. The arbitrator's decision will be final and binding and may be entered as a judgment in any court of competent jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">19. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. To the extent any Dispute is not subject to arbitration, you consent to exclusive jurisdiction and venue in the state and federal courts located in Delaware.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">20. Apple App Store — Additional Terms</h2>
            <p>
              If you download the Service from Apple's App Store, the following additional terms apply:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>These Terms are between you and Axiom only, not with Apple Inc. Apple is not responsible for the Service or its content.</li>
              <li>Apple has no obligation to provide maintenance or support for the Service.</li>
              <li>In the event the Service fails to conform to any applicable warranty, you may notify Apple and Apple will refund the purchase price (if any) for the app. To the maximum extent permitted by law, Apple has no other warranty obligation.</li>
              <li>Apple is not responsible for addressing any claims by you or any third party relating to the Service, including product liability claims, consumer protection claims, or intellectual property infringement claims.</li>
              <li>Apple and Apple's subsidiaries are third-party beneficiaries of these Terms and, upon your acceptance, Apple will have the right to enforce these Terms against you as a third-party beneficiary.</li>
              <li>You represent and warrant that you are not located in a country subject to a U.S. Government embargo or designated as a "terrorist supporting" country, and that you are not listed on any U.S. Government prohibited or restricted parties list.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">21. Miscellaneous</h2>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li><strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy, constitute the entire agreement between you and Axiom regarding the Service.</li>
              <li><strong>Severability:</strong> If any provision of these Terms is found invalid or unenforceable, the remaining provisions remain in full force and effect.</li>
              <li><strong>Waiver:</strong> Failure to enforce any provision of these Terms shall not constitute a waiver of that provision.</li>
              <li><strong>Assignment:</strong> You may not assign your rights or obligations under these Terms without our prior written consent. We may assign our rights freely.</li>
              <li><strong>Force Majeure:</strong> We are not liable for failures or delays resulting from causes beyond our reasonable control.</li>
              <li><strong>No Professional Relationship:</strong> Use of the Service does not create a coach-client, therapist-patient, doctor-patient, or any other professional relationship between you and Axiom or any of its employees.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">22. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. We will notify you of material changes by posting the updated Terms with a revised "Last updated" date and, where appropriate, by sending an in-app notification or email. Your continued use of the Service after the effective date of changes constitutes your acceptance. If you do not agree to the revised Terms, you must stop using the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">23. Contact Us</h2>
            <p>For questions about these Terms, contact us at:</p>
            <p className="mt-2">
              <strong>Email:</strong>{" "}
              <a href="mailto:legal@axiomtraining.io" className="text-primary hover:underline">legal@axiomtraining.io</a>
            </p>
          </section>
        </div>

        <footer className="border-t py-10 mt-12">
          <div className="flex flex-col gap-2 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center gap-3">
              <BrandLogo height={24} className="h-6 w-auto" />
              <span>Axiom — AI-Powered Strength Training</span>
            </div>
            <div className="flex items-center gap-3">
              <Link href="/" className="hover:text-foreground">Home</Link>
              <Link href="/privacy" className="hover:text-foreground">Privacy Policy</Link>
              <Link href="/pricing" className="hover:text-foreground">Pricing</Link>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}
