// Every UI string for the personal-training dashboard. Sentence case, no
// emoji, no exclamation marks (handoff §13). Client-facing status language is
// "Might need support" — never "at risk" or "churning" (§6.2).

import type { ClientStatus, EngagementTrend, RosterFilter, TimelineKind } from './types';

export const STATUS_LABEL: Record<ClientStatus, string> = {
  support: 'Might need support',
  new: 'New',
  onPlan: 'On plan',
  paused: 'Paused',
  notJoined: 'Not joined',
};

export const FILTER_LABEL: Record<RosterFilter, string> = { all: 'All', ...STATUS_LABEL };

/** Chip order on the roster (§6.2). */
export const ROSTER_FILTERS: RosterFilter[] = ['all', 'support', 'new', 'onPlan', 'paused', 'notJoined'];

export const TREND_LABEL: Record<EngagementTrend, string> = {
  rising: 'Rising',
  steady: 'Steady',
  falling: 'Falling',
};

export const KIND_LABEL: Record<TimelineKind, string> = {
  workout: 'Workout',
  checkin: 'Check-in',
  message: 'Message',
  measurement: 'Measurement',
  photos: 'Photos',
  program: 'Program',
  note: 'Note',
  billing: 'Billing',
};

/** Kinds the timeline can actually produce; photos and billing have no data source yet. */
export const TIMELINE_FILTER_KINDS: TimelineKind[] = ['workout', 'checkin', 'message', 'measurement', 'program', 'note'];

export const COPY = {
  productName: 'Personal training',
  nav: {
    briefing: 'Briefing',
    clients: 'Clients',
    checkIns: 'Check-ins',
    progress: 'Progress',
    anakin: 'Ask Anakin',
    comingSoon: 'Coming soon',
  },
  roster: {
    title: 'Clients',
    invite: 'Invite client',
    searchPlaceholder: 'Search clients',
    countLine: (n: number) => (n === 1 ? '1 client' : `${n} clients`),
    emptyTitle: 'No clients yet.',
    emptyBody: 'Invite a client to see their training here.',
    noMatches: 'No clients match that filter.',
    columns: { client: 'Client', status: 'Status', program: 'Program', engagement: 'Engagement', lastCheckIn: 'Last check-in' },
    noProgram: 'No program yet',
    never: 'None yet',
    loadFailed: 'Could not load your clients.',
    retry: 'Try again',
  },
  invite: {
    title: 'Invite a client',
    body: 'They join with their Axiom account. You will see their workouts, check-ins, bodyweight and injuries.',
    emailLabel: 'Client email (optional)',
    emailHint: 'If you add an email, only that account can use the link.',
    generate: 'Create invite link',
    copy: 'Copy link',
    copied: 'Copied',
    share: 'Share link',
    shareMessage: (practice: string, link: string) => `Join ${practice} on Axiom: ${link}`,
    expires: (when: string) => `Link expires ${when}.`,
    failed: 'Could not create the invite.',
  },
  join: {
    title: (practice: string) => `Join ${practice}`,
    body: (trainer: string) =>
      `${trainer} will be able to see your workouts, check-ins, bodyweight, program and any injuries you have listed, and can message you.`,
    accept: 'Share my training and join',
    decline: 'Not now',
    joined: 'You are connected.',
    invalid: 'This invite is no longer valid.',
    wrongAccount: 'This invite was sent to a different email address.',
  },
  setup: {
    title: 'Set up your practice',
    body: 'Give your practice a name. Clients see it when you invite them.',
    nameLabel: 'Practice name',
    namePlaceholder: 'Kofi Mensah Coaching',
    submit: 'Create practice',
    failed: 'Could not create the practice.',
  },
  unavailable: {
    title: 'Personal training is not enabled for this account yet.',
    body: 'If you coach clients and want access, get in touch with the Axiom team.',
  },
  dossier: {
    tabs: { overview: 'Overview', timeline: 'Timeline', program: 'Program', notes: 'Notes' },
    message: 'Message',
    messageTitle: (name: string) => `Message ${name}`,
    messagePlaceholder: 'Write a message',
    messageSend: 'Send message',
    requestCheckIn: 'Request check-in',
    checkInRequested: 'Check-in sent.',
    checkInAlready: 'They already have a check-in waiting.',
    summary: 'Summary',
    summaryBasis: 'What is this based on?',
    updated: (when: string) => `Updated ${when}`,
    keyStats: 'Key stats',
    currentBlock: 'Current block',
    blockProgress: (week: number, weeks: number) => `Week ${week} of ${weeks}`,
    openItems: 'Open items',
    noOpenItems: 'Nothing is waiting on you for this client.',
    openBriefing: 'Handle in briefing',
    recentPrs: 'Recent PRs',
    noProgram: 'This client has no program yet.',
    programGoal: 'Goal',
    programWeek: (week: number, weeks: number) => `Week ${week} of ${weeks}`,
    programDays: (n: number) => `${n} ${n === 1 ? 'day' : 'days'} a week`,
    currentPhase: 'Current phase',
    pendingChanges: 'Suggested changes waiting on the client',
    pendingHelp: 'Axiom proposed these in their app. The client accepts or declines them; you can recommend one by message.',
    programReadOnly: 'Programs are edited by the client with Axiom in their app. Message them to recommend a change.',
    notesHelp: 'Private to your practice. Clients never see these.',
    notePlaceholder: 'Add a note about this client',
    addNote: 'Add note',
    saveNote: 'Save',
    editNote: 'Edit',
    deleteNote: 'Delete',
    cancel: 'Cancel',
    noNotes: 'No notes yet.',
    loadFailed: 'Could not load this.',
  },
  timeline: {
    breadcrumb: 'Clients',
    tab: 'Timeline',
    loadEarlier: 'Load earlier',
    empty: 'Nothing logged yet.',
    emptyFiltered: 'Nothing of that kind yet.',
    allKinds: 'All',
    tenure: (when: string) => `Client since ${when}`,
    noContraindications: 'No injuries listed',
    cleared: 'cleared',
    loadFailed: 'Could not load this timeline.',
    notFound: 'This client is not on your roster.',
  },
  briefing: {
    greeting: (name: string) => `Let's get to work, ${name}.`,
    summary: (attention: number, look: number, onPlan: number) =>
      `${attention} ${attention === 1 ? 'client needs' : 'clients need'} you today. ${look} ${look === 1 ? 'is' : 'are'} worth a look. ${onPlan} ${onPlan === 1 ? 'is' : 'are'} on plan.`,
    meter: (done: number, total: number) => `${done} of ${total} handled`,
    attention: 'Needs attention',
    look: 'Worth a look',
    allClearGroup: (n: number) => `All clear · ${n}`,
    suggests: 'Axiom suggests',
    why: 'Why am I seeing this?',
    whyHeading: "Why you're seeing this",
    sources: 'Sources',
    openClient: 'Open timeline',
    markHandled: 'Mark handled',
    dismiss: 'Dismiss',
    undo: 'Undo',
    nothingSends: 'Nothing sends without you',
    basedOn: (when: string) => `Based on data through ${when}`,
    allClearTitle: 'All clear.',
    allClearBody: 'No one needs you this morning. Everyone is training to plan.',
    statCheckIns: 'Check-ins this week',
    statAdherence: '7-day adherence',
    statPrs: 'PRs this week',
    askAnakin: 'Ask Anakin about your roster',
    staleBanner: (when: string, logged: number) =>
      `Showing ${when}'s briefing. ${logged} ${logged === 1 ? 'client has' : 'clients have'} logged since then.`,
    staleWorking: 'Today\'s briefing is being written.',
    staleFailed: 'Today\'s briefing could not be generated.',
    retry: 'Try again',
    reading: (n: number) => `Reading ${n} ${n === 1 ? 'client\'s' : 'clients\''} last 24 hours`,
    sourceLabels: { workouts: 'Workouts', checkIns: 'Check-ins', messages: 'Messages', programs: 'Programs' },
    ready: (n: number) => `Briefing ready, ${n} ${n === 1 ? 'item' : 'items'}`,
    setupTitle: 'Set up your first briefing',
    setupBody: 'Your briefing fills in once clients are training. Start here.',
    setupSteps: ['Invite your clients', 'Check their injuries are on file', 'Set a check-in cadence', 'Choose what interrupts you'],
    sampleLabel: 'What a briefing card looks like',
    morningQuestions: 'Your morning questions',
    keyboardHint: 'J and K move between cards · A sends · D dismisses · W shows why · Enter opens the client',
    sendFailed: 'That did not send. Try again.',
  },
  draft: {
    send: 'Send',
    shorter: 'Shorter',
    sent: 'Sent',
    sending: 'Sending',
    undo: 'Undo',
    label: 'Draft message',
    discarded: 'Draft discarded',
  },
  checkIns: {
    title: 'Check-ins',
    inbox: 'Inbox',
    configure: 'Configure',
    empty: 'No check-ins yet.',
    emptyBody: 'Switch on a schedule, or ask a client for one now.',
    request: 'Request a check-in',
    requestTitle: 'Request a check-in',
    requestBody: 'Each client you pick gets a message from you with a link to their check-in.',
    requestSend: (n: number) => `Send to ${n} ${n === 1 ? 'client' : 'clients'}`,
    requested: (n: number) => `Check-in sent to ${n} ${n === 1 ? 'client' : 'clients'}.`,
    axiomRead: 'Axiom read this',
    answers: 'Their answers',
    markRead: 'Mark read, no reply',
    reviewed: 'Reviewed',
    sendRoutine: (n: number) => `Send all routine replies (${n})`,
    routineSent: (n: number) => `${n} routine ${n === 1 ? 'reply' : 'replies'} sent.`,
    missedTitle: (n: number) => `${n} missed ${n === 1 ? 'check-in' : 'check-ins'}`,
    classification: { flag: 'Needs attention', look: 'Worth a look', routine: 'Routine' },
    select: 'Choose a check-in to read it.',
    scheduleDefault: 'All clients',
    scheduleOff: 'Off',
    scheduleOn: 'On',
    cadence: 'Cadence',
    frequency: { weekly: 'Every week', biweekly: 'Every two weeks' },
    day: 'Day',
    time: 'Time',
    questions: 'Questions',
    addQuestion: 'Add question',
    questionTypes: { text: 'Free text', scale: 'Scale 1 to 5', number: 'Number' },
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove',
    missedRules: 'If a check-in is missed',
    nudgeAfter: 'Nudge after (hours)',
    flagAfter: 'Flag in briefing after (hours)',
    pauseAfter: 'Pause nudges after this many misses',
    save: 'Save schedule',
    saved: 'Schedule saved.',
    activeHint: 'When this is on, clients get a message from you with their check-in link at the time you set.',
    footer: 'Clients answer on the web from the link in the message. The questions are the same for everyone on this schedule.',
    addOverride: 'Add a client override',
    removeOverride: 'Remove override',
    loadFailed: 'Could not load check-ins.',
  },
  checkInForm: {
    title: (trainer: string) => `Check-in for ${trainer}`,
    submit: 'Send check-in',
    done: 'Thanks. Your trainer has it.',
    already: 'This check-in has already been sent.',
    notFound: 'This check-in is not available.',
    scaleLow: 'Low',
    scaleHigh: 'High',
  },
  progress: {
    title: 'Progress',
    roster: 'Roster',
    report: 'Client report',
    kpiProgressing: 'Progressing',
    kpiPlateau: 'On a plateau',
    kpiPrs: 'PRs this month',
    onlyPlateaus: 'Only plateaus and regressions',
    viewTable: 'Table',
    viewGrid: 'Grid',
    columns: { client: 'Client', e1rm: 'Est. 1RM', trend: (w: number) => `${w}-week trend`, change: 'Change', adherence: 'Adherence', status: 'Status' },
    status: { progressing: 'Progressing', plateau: 'Plateau', regressing: 'Regressing', noData: 'Not enough data' },
    empty: 'No clients to show.',
    seriesAlt: (name: string, lift: string, status: string) => `${name}, ${lift}: ${status}`,
    loadFailed: 'Could not load progress.',
    reportClient: 'Client',
    reportMonth: 'Month',
    prLog: 'PR log',
    noPrs: 'No PRs this month.',
    measurements: 'Bodyweight',
    noMeasurements: 'No bodyweight logged this month.',
    preview: 'What your client will see',
    note: (trainer: string) => `From ${trainer}`,
    notePlaceholder: 'Add a personal note',
    saveNote: 'Save note',
    approveSend: 'Approve and send',
    statusDraft: 'Draft',
    statusSent: 'Sent',
    pickClient: 'Choose a client to draft their report.',
  },
  anakin: {
    title: 'Ask Anakin',
    heading: 'What do you want to know about your roster?',
    placeholder: 'Ask about your clients',
    send: 'Ask',
    newQuestion: 'New question',
    runsEveryMorning: 'Runs every morning',
    noScheduled: 'Nothing scheduled yet.',
    recent: 'Recent',
    scope: 'Scope',
    scopes: { all: 'All clients', new: 'New clients', support: 'Might need support' },
    starters: [
      { category: 'Plateaus', text: 'Who is on a plateau?' },
      { category: 'Engagement', text: 'Who has not trained in 7 days?' },
      { category: 'Safety', text: 'Who mentioned pain in the last 14 days?' },
      { category: 'Programming', text: 'Whose program is ending soon?' },
    ],
    applyFilter: 'Apply as roster filter',
    runEveryMorning: 'Run every morning',
    scheduledDone: 'Scheduled',
    basedOn: (sources: string) => `Based on ${sources}`,
    filterBanner: (question: string) => `Ask Anakin filter · ${question}`,
    clearFilter: 'Clear',
    failed: 'Something went wrong answering that.',
    remove: 'Remove',
    thinking: 'Thinking',
    threads: 'Questions',
  },
  notifications: {
    title: 'Notifications',
    bell: 'Notifications',
    needsYou: 'Needs you now',
    nothing: 'Nothing needs you right now.',
    held: (n: number) => `${n} ${n === 1 ? 'update' : 'updates'} held for tomorrow's briefing`,
    quiet: (n: number) => `${n} ${n === 1 ? 'log' : 'logs'} recorded quietly`,
    settings: 'Notification settings',
    markAllRead: 'Mark all read',
    tiers: { immediate: 'Immediately', briefing: 'In briefing', timeline: 'Timeline only' },
    tierHelp: {
      immediate: 'Reaches you straight away',
      briefing: 'Held for your next morning briefing',
      timeline: 'Recorded on the client timeline, nothing sent',
    },
    locked: 'Safety events always reach you',
    estimate: (n: number) => `About ${n} ${n === 1 ? 'alert' : 'alerts'} a week at these settings`,
    perWeek: (n: number) => `${n} a week`,
    channels: 'Channels',
    push: 'Push notifications',
    email: 'Email',
    quietHours: 'Quiet hours',
    quietHelp: 'Immediate alerts wait in the bell during quiet hours. Safety events still come through.',
    from: 'From',
    to: 'To',
    overrides: 'Per-client overrides',
    overridesHelp: 'Make one client louder or quieter for a while.',
    addOverride: 'Add override',
    allEvents: 'Every event',
    overrideNote: 'Note (optional)',
    overrideNotePlaceholder: 'until knee is cleared',
    removeOverride: 'Remove',
    saved: 'Saved.',
    saveFailed: 'Could not save that change.',
    loadFailed: 'Could not load notification settings.',
  },
  import: {
    title: 'Import clients',
    entry: 'Import clients',
    intro: 'Upload the spreadsheet you keep your clients in. Axiom works out how it is laid out, shows you what it found, and imports nothing until you confirm.',
    formats: 'Excel (.xlsx) or CSV. If your file is an older .xls, save it as .xlsx first.',
    choose: 'Choose a file',
    reading: 'Reading your file',
    working: 'Working out how your sheet is laid out',
    notReadable: 'That file could not be read. Save it as .xlsx or .csv and try again.',
    tooBig: 'That file is too large to import in one go. Split it into smaller files.',
    review: 'Check what was found',
    found: (clients: number, workouts: number, weights: number) =>
      `${clients} ${clients === 1 ? 'client' : 'clients'}, ${workouts} ${workouts === 1 ? 'session' : 'sessions'} and ${weights} bodyweight ${weights === 1 ? 'entry' : 'entries'} found.`,
    statClients: 'Clients',
    statSessions: 'Sessions',
    statWeights: 'Bodyweight entries',
    statSkipped: 'Rows skipped',
    assumptions: 'What was assumed',
    warnings: 'What could not be read',
    clients: 'Clients found',
    columns: { client: 'Client', email: 'Email', sessions: 'Sessions', range: 'Dates', weights: 'Bodyweight' },
    noEmail: 'No email',
    alreadyClient: 'Already your client',
    alreadyClientHelp: 'Their history will be added to the client you already have.',
    notJoinedHelp: 'Anyone who is not already your client on Axiom is added as Not joined. You can see their history straight away and invite them when you are ready.',
    latest: 'Most recent sessions',
    sheets: 'How each sheet was read',
    sheetsHelp: 'Change these if something was read wrongly, then apply.',
    kind: 'This sheet holds',
    kinds: { workouts: 'Training log', bodyweight: 'Bodyweight log', clients: 'Client list', ignore: 'Nothing to import' },
    headerRow: 'Header row',
    clientFrom: 'Client name comes from',
    clientFromOptions: { column: 'A column', sheetName: 'The sheet name' },
    unit: 'Weights are in',
    units: { kg: 'Kilograms', lb: 'Pounds' },
    dateOrder: 'Dates are written',
    dateOrders: { dmy: 'Day / month / year', mdy: 'Month / day / year', ymd: 'Year-month-day' },
    fields: {
      client: 'Client name', email: 'Email', phone: 'Phone', goal: 'Goal', injuries: 'Injuries', notes: 'Notes', date: 'Date',
      exercise: 'Exercise', sets: 'Sets', reps: 'Reps', weight: 'Load', rpe: 'RPE', sessionTitle: 'Session name', bodyweight: 'Bodyweight',
    },
    notInSheet: 'Not in this sheet',
    apply: 'Apply changes',
    confirm: (n: number) => `Import ${n} ${n === 1 ? 'client' : 'clients'}`,
    cancel: 'Start over',
    nothing: 'Nothing was found to import. Check how each sheet was read below.',
    done: (clients: number, workouts: number) => `Imported ${clients} ${clients === 1 ? 'client' : 'clients'} and ${workouts} ${workouts === 1 ? 'session' : 'sessions'}.`,
    doneHelp: 'Clients without an Axiom account are on your roster as Not joined.',
    viewRoster: 'View roster',
    undo: 'Undo this import',
    undone: 'Import undone.',
    past: 'Past imports',
    pastUndone: 'Undone',
    failed: 'Something went wrong with the import.',
    inviteProspect: 'Invite to Axiom',
    inviteTitle: (name: string) => `Invite ${name} to Axiom`,
    inviteBody: 'When they accept, what you imported for them appears alongside what they log. Only this email address can use the link.',
    inviteEmail: 'Their email address',
    inviteCreate: 'Create invite link',
    drop: 'or drop it here',
    sheetSample: 'First rows of this sheet',
    willAdd: (n: number) => `${n} will be added as Not joined.`,
    importedOn: (when: string) => `Imported ${when}`,
    notImported: 'Not imported',
    counts: (clients: number, workouts: number) => `${clients} ${clients === 1 ? 'client' : 'clients'} · ${workouts} ${workouts === 1 ? 'session' : 'sessions'}`,
    undoConfirm: 'This removes everything this file added, including Not joined clients it created.',
    notJoinedBanner: (name: string) => `${name} has not joined Axiom yet. This is their imported history.`,
  },
  exit: {
    myTraining: 'Go to my training',
    menu: 'Account',
  },
  login: {
    toggle: 'Sign in as a personal trainer',
    cancel: 'Cancel personal trainer sign-in',
    subtitle: 'Sign in to your trainer dashboard',
    submit: 'Sign in to trainer dashboard',
    divider: 'Personal trainers',
  },
} as const;
