// Pre-rendered dither assets (generated by scripts/generate-dithered.js), keyed
// by the RAW photo's module id. DitherImage looks the baked version up by the
// `source` it's handed, so it can render a cheap <Image> instead of a live Skia
// canvas + shader — far cheaper to mount, so scene transitions stay smooth.
//
// To regenerate after changing a photo or a wash: `node scripts/generate-dithered.js`.
import { PHOTOS } from '../photos/manifest';

export const DITHERED: Record<number, ReturnType<typeof require>> = {
  [PHOTOS.gymOldschool as unknown as number]: require('./gym-oldschool.png'),
  [PHOTOS.nutrition as unknown as number]:    require('./nutrition.png'),
  [PHOTOS.coachSquat as unknown as number]:   require('./coach-squat.png'),
  [PHOTOS.hypeDuo as unknown as number]:      require('./hype-duo.png'),
  [PHOTOS.equipGymleco as unknown as number]: require('./equip-gymleco.png'),
  [PHOTOS.physiqueBack as unknown as number]: require('./physique-back.png'),
  [PHOTOS.rackSmith as unknown as number]:    require('./rack-smith.png'),
};
